### ISSUE TITLE
Typo in nginx configuration (amd64)

### ISSUE THREAD

**Issue by dersimn** [holgerimbery/parea#7]
`parea/dockerized/nginx/run.sh` - [line 4](https://github.com/holgerimbery/parea/blob/0534298e8e116bdb59de8d87a96528fd6880de04/dockerized/nginx/run.sh#L4)

    -v ~/parea/config/parea-admin/config:/etc/ngnix \

vs.

    -v ~/parea/config/parea-admin/config:/etc/nginx \

**Comment by holgerimbery** [comment]
Thank you Simon !
#f3c6705
#40de8dd

Stupid me - every time the same mistake.... I will write it on a post-it note and place it on my monitor .-)
