### ISSUE TITLE
Maybe use docker-compose for deployment?

### ISSUE THREAD

**Issue by dersimn** [holgerimbery/parea#8]
<https://docs.docker.com/compose/overview>

I'm using this to [deploy OpenHAB](https://github.com/dersimn/OpenHAB-Docker-Suite/blob/master/docker-compose.yml), but I've been struggling with myself for quite a while to take a look at @hobbyquaker's mqtt-based projects.

**Comment by holgerimbery** [comment]
You are right, docker compose could be a solution - I'm  struggling with myself, as I want to use the template feature I'm using for the add-ons as well as for the basis. 
May be I should mix it, portainer and mosquitto with docker compose and the rest with portainer templates.

**Comment by holgerimbery** [comment]
realized with version v1.2 (Juan-les-Pins)
